cloudyspells/PSRule.Rules.AzureDevOps

README.md

Update `README.md`  with correct usage command

Fix usage command

---

src/PSRule.Rules.AzureDevOps/Functions/DevOps.Tasks.VariableGroups.ps1
src/PSRule.Rules.AzureDevOps/PSRule.Rules.AzureDevOps.psm1
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Pipelines.Core.UseYaml.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Pipelines.Environments.Description.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Pipelines.Environments.ProductionCheckProtection.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Pipelines.Environments.ProductionHumanApproval.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyAllowSelfApproval.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyCommentResolution.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyEnforceLinkedWorkItems.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyIsEnabled.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyMergeStrategy.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyMinimumReviewers.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.BranchPolicyResetVotes.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.HasBranchPolicy.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.License.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Repos.Readme.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.ServiceConnections.Description.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.ServiceConnections.ProductionCheckProtection.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.ServiceConnections.ProductionHumanApproval.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.ServiceConnections.Scope.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Tasks.VariableGroup.Description.md
src/PSRule.Rules.AzureDevOps/en-US/Azure.DevOps.Tasks.VariableGroup.NoKeyVaultNoSecrets.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Core.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Tasks.VariableGroups.Rule.ps1

This release adds basic support for variable groups in Azure DevOps.

Variable group support

---

.github/workflows/module-ci.yml
README.md
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Pipelines.Core.ps1
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Repos.ps1
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Tasks.VariableGroups.ps1
src/PSRule.Rules.AzureDevOps/PSRule.Rules.AzureDevOps.psm1
tests/PSRule.Rules.AzureDevOps.Tests.ps1

- This PR introduces Pester testing and a QA workflow in GitHub

Working on tests and pr workflow

---

.github/workflows/module-ci.yml
README.md
sonar-project.properties

- Added SonarCloud to aid in secure software development

Add sonarcloud

---

src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.ServiceConnections.WorkloadIdentityFederation.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.ServiceConnections.WorkloadIdentityFederation.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.ServiceConnection.Rule.ps1
tests/Rules.Tests.ps1

- Added rule: `Azure.DevOps.ServiceConnections.WorkloadIdentityFederation`

Add rule: Azure.DevOps.ServiceConnections.WorkloadIdentityFederation

---

src/PSRule.Rules.AzureDevOps/Functions/DevOps.Repos.ps1
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.GitHubAdvancedSecurityBlockPushes.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.GitHubAdvancedSecurityEnabled.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.GitHubAdvancedSecurityBlockPushes.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.GitHubAdvancedSecurityEnabled.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Releases.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Repos.Rule.ps1
tests/PSRule.Rules.AzureDevOps.Tests.ps1
tests/Rules.Tests.ps1

- Add support for auditing Azure DevOps GitHub Advanced security settings
- Fixes to Release definition rules

Add Ghas support and debug some rules

---

README.md
pipelines/README.md

- Update contributing and License info and links
- Fix var name in pipelines sample docs
- Some minor text updates

Minor README updates

---

README.md

Fix some minor issues in the `README.md`

Fix typo + enhancements

---

README.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.Environments.ProductionBranchLimit.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.ServiceConnections.ProductionBranchLimit.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.Environments.ProductionBranchLimit.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.ServiceConnections.ProductionBranchLimit.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Environments.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.ServiceConnection.Rule.ps1
tests/Rules.Tests.ps1

This PR adds rules for checks on branch controls for production scoped service connections and environments
Best pratices state these resources should be scoped to specific controlled branches
Pester tests have been included
- [-] Bug fix (non-breaking change which fixes an issue)
- [-] Breaking change (fix or feature that would cause existing functionality to change)

Add rules for branch control checks

---

README.md
docs/security-best-practices.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Tasks.VariableGroup.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Tasks.VariableGroup.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Tasks.VariableGroups.Rule.ps1
tests/Rules.Tests.ps1

This PR adds secrets scanning for _variable groups_. Variables are scanned for some regex patterns including SQL, Event Hub, Storage Account, Service Bus connection strings and keys and PAT tokens exposed in non-secret variables.
This improves intelligence on security posture.
Pester tests and practical tests involving both positive and negative results

Feature: Variable group secret scanning

---

README.md
docs/security-best-practices.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.BranchPolicyRequireBuild.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.BranchPolicyRequireBuild.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Repos.Rule.ps1
tests/Rules.Tests.ps1

Adds a rule for branch policy requiring a build/pipeline to succeed before merging a PR
This is a recommendation in the Azure DevOps security best practices.
Manual and automated testing on repositories with- and without the branch policy in place

Feature: Repo branch policy require build

---

src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.Core.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.Releases.Definition.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.Core.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.Releases.Definition.NoPlainTextSecrets.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Core.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Releases.Rule.ps1
tests/Rules.Tests.ps1

Feature: Rules for secrets in GUI designer vars

---

README.md
docs/security-best-practices.md

Fix: update missing rule refs

---

src/PSRule.Rules.AzureDevOps/Functions/DevOps.Pipelines.Settings.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Settings.Rule.ps1

This migrates export of project pipeline settings to the REST API instead of the UI API
Fixes feature #48 
REST API allows fine grained PAT over Full Access PAT
Pester tests in project workflow

Fix feature #48 - pipeline settings REST

---

.github/workflows/module-ci.yml
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Pipelines.Core.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Core.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Pipelines.Releases.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Tasks.VariableGroups.Rule.ps1
tests/Rules.Tests.ps1

This PR enhances secret detection to include:
- Azure Cognitive Services API keys
- Azure OpenAI API keys
- MongoDB connection string
- MySQL connection string'
- PostgreSQL connection string
- Redis connection string
- AWS ID
- PEM format keys
Secrets are detected in Build and Release definitions and in Variable Groups.
This fixes #42 
Secrets should not be stored in plain text variables
Pester Unit tests

Fix #42 - Enhance secret detection

---

.github/workflows/publish-on-release.yml

FIx release nr

---

.github/workflows/publish-on-release.yml

FIx publish params

---

src/PSRule.Rules.AzureDevOps/Functions/Common.ps1
src/PSRule.Rules.AzureDevOps/PSRule.Rules.AzureDevOps.psm1

Fix cmdlet export

---

.github/workflows/psrule-monitor.yml

Set shell to pwsh

---

src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.PipelineYaml.AgentPoolVersionNotLatest.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.Settings.RequireCommentForPullRequestFromFork.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Pipelines.Settings.RestrictSecretsForPullRequestFromFork.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.BranchPolicyCommentResolution.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.BranchPolicyMergeStrategy.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.License.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Readme.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.ServiceConnections.ClassicAzure.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.ServiceConnections.Description.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.ServiceConnections.WorkloadIdentityFederation.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Tasks.VariableGroup.Description.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Tasks.VariableGroup.NoKeyVaultNoSecrets.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.PipelineYaml.AgentPoolVersionNotLatest.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.Settings.RequireCommentForPullRequestFromFork.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Pipelines.Settings.RestrictSecretsForPullRequestFromFork.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.BranchPolicyCommentResolution.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.BranchPolicyMergeStrategy.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.License.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Repos.Readme.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.ServiceConnections.ClassicAzure.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.ServiceConnections.Description.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.ServiceConnections.WorkloadIdentityFederation.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Tasks.VariableGroup.Description.md
src/PSRule.Rules.AzureDevOps/nl/Azure.DevOps.Tasks.VariableGroup.NoKeyVaultNoSecrets.md

Refine rule severity

---

docs/branch-strategy-suppression.md
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Repos.ps1
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyAllowSelfApproval.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyCommentResolution.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyEnforceLinkedWorkItems.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyIsEnabled.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyMergeStrategy.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyMinimumReviewers.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyRequireBuild.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.BranchPolicyResetVotes.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.Branch.HasBranchPolicy.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyAllowSelfApproval.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyCommentResolution.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyEnforceLinkedWorkItems.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyIsEnabled.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyMergeStrategy.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyMinimumReviewers.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyRequireBuild.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.DefaultBranchPolicyResetVotes.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Repos.HasDefaultBranchPolicy.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Repo.Branches.Rule.ps1
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Repos.Rule.ps1
tests/DevOps.Repos.Tests.ps1
tests/Rules.Tests.ps1

This PR adds all repository branches to the repo export and new rules to cover the new branch objects.
Fixes #72 
A decent branch strategy needs more controls than only the default branch.
Pester tests have been updated

Add branch export

---

pipelines/azure-pipelines.yml

Fix Azure DevOps example pipeline for version 0.3.0 upwards

Add Connect-AzDevOps

---

README.md
docs/token-permissions.md
example/best-practice/ps-rule.yaml
src/PSRule.Rules.AzureDevOps/Functions/Common.ps1
src/PSRule.Rules.AzureDevOps/Functions/DevOps.Groups.ps1
src/PSRule.Rules.AzureDevOps/PSRule.Rules.AzureDevOps.psm1
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Groups.ProjectAdmins.MaxMembers.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Groups.ProjectAdmins.MinMembers.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.Groups.ProjectValidUsers.DoNotAssignMemberOfOtherGroups.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.Groups.Rule.ps1
tests/Common.Tests.ps1
tests/DevOps.Groups.Tests.ps1
tests/Rules.Tests.ps1

This PR adds Export of AzDo groups with their members and memberOf determined.
Fixes #41 
Groups should be included for at least some basic rules
Pester tests have been included in CI

Group export and basic rules

---

example/best-practice/ps-rule.yaml
src/PSRule.Rules.AzureDevOps/Functions/DevOps.RetentionSettings.ps1
src/PSRule.Rules.AzureDevOps/PSRule.Rules.AzureDevOps.psm1
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.RetentionSettings.ArtifactMinimumRetentionDays.md
src/PSRule.Rules.AzureDevOps/en/Azure.DevOps.RetentionSettings.PullRequestRunsMinimumRetentionDays.md
src/PSRule.Rules.AzureDevOps/rules/AzureDevOps.RetentionSettings.Rule.ps1
tests/DevOps.Groups.Tests.ps1
tests/DevOps.RetentionSettings.Tests.ps1
tests/Rules.Tests.ps1

Adds export for the projects retention settings regarding pull-request builds and artifacts. Adds 2 rules:
- `Azure.DevOps.RetentionSettings.ArtifactMinimumRetentionDays`
- `Azure.DevOps.RetentionSettings.PullRequestRunsMinimumRetentionDays`
Fixes #88 
Retention settings are a part of the projects compliance posture
Pester tests in CI and developer workstation

Fix Add artifact and build retention export and rules #88

---

README.md

Add PsrAzDo-workbooks ref

---

README.md

Updated README with workbooks section

Update workbooks reference

---

src/PSRule.Rules.AzureDevOps/Functions/DevOps.Repos.ps1
tests/DevOps.Repos.Tests.ps1

Fix Bug: Repo export fails when repository contains a single branch #97

---

.github/workflows/psrule-monitor.yml

This PR is for internal project use to aid the spinoff Azure Monitor workbooks project with a daily feed of the Test environment AzDo organization instead of only the single project. 
None
People like GUIs 😄

Export AzDo org data instead of project only

---

src/PSRule.Rules.AzureDevOps/Functions/DevOps.Repos.ps1
tests/DevOps.Repos.Tests.ps1

This PR fixes an undocumented issue when running `main` branch with an empty unintialized repo.
None
Bugfix for unreleased version
Pester test for this scenario has been added as this was missing.

Fix issue with unintialized repos
